### ISSUE TITLE
Fail to install in Vuetify project

### ISSUE THREAD

**Issue by nabanoub** [sneko/dsfr-connect#2]
## Current Behavior

trying to ` npm install dsfr-connect ` , fails :

```
npm ERR! code 1
npm ERR! path C:\Repos\canel2.1\canel-front\node_modules\dsfr-connect
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c ts-node -r tsconfig-paths/register ./scripts/setup.ts
npm ERR! node:internal/modules/cjs/loader:1080
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module './setup.ts'
npm ERR! Require stack:
npm ERR! - C:\Repos\canel2.1\canel-front\node_modules\dsfr-connect\scripts\imaginaryUncacheableRequireResolveScript
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
npm ERR!     at Function.resolve (node:internal/modules/cjs/helpers:127:19)
npm ERR!     at requireResolveNonCached (C:\Repos\canel2.1\canel-front\node_modules\ts-node\dist\bin.js:549:16)
npm ERR!     at getProjectSearchDir (C:\Repos\canel2.1\canel-front\node_modules\ts-node\dist\bin.js:519:40)
npm ERR!     at phase3 (C:\Repos\canel2.1\canel-front\node_modules\ts-node\dist\bin.js:267:27)
npm ERR!     at bootstrap (C:\Repos\canel2.1\canel-front\node_modules\ts-node\dist\bin.js:47:30)
npm ERR!     at main (C:\Repos\canel2.1\canel-front\node_modules\ts-node\dist\bin.js:33:12)
npm ERR!     at Object.<anonymous> (C:\Repos\canel2.1\canel-front\node_modules\ts-node\dist\bin.js:579:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     'C:\\Repos\\canel2.1\\canel-front\\node_modules\\dsfr-connect\\scripts\\imaginaryUncacheableRequireResolveScript'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v18.17.1
```

## Environment

- Version: 1.1.0
- Platform:  Windows 10
- Node.js Version: v18.17.1

**Comment by sneko** [comment]
@nabanoub good catch! I recently switched `prepare` and `postinstall` (the latter also runs at package installation, which I didn't want).

Thank you 👍 , just released a new version.
